---
- name: install preconditions
  dnf:
    state: latest
    name:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - dkms
      - acpid
      - libglvnd-glx
      - libglvnd-opengl
      - libglvnd-devel
      - pkgconfig
- name: enable rpm fusion
  dnf:
    name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-39.noarch.rpm 
    state: present

- name: enable rpm fusion
  dnf:
    name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-39.noarch.rpm
    state: present

- name: makecache
  command: dnf makecache

- name: install nvidia drivers
  dnf:
    state: latest
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda
# - name: Add nvidia repo
#   dnf:
#     enablerepo: https://developer.download.nvidia.com/compute/cuda/repos/fedora37/x86_64/cuda-fedora37.repo
#     disable_gpg_check: yes
#     state: present
# - name: install preconditions for nvidia
#   dnf:
#     state: latest
#     name:
#       - kernel-headers
#       - kernel-devel
#       - tar
#       - bzip2
#       - make
#       - automake
#       - gcc
#       - gcc-c++
#       - pciutils
#       - elfutils-libelf-devel
#       - libglvnd-opengl
#       - libglvnd-glx
#       - libglvnd-devel
#       - acpid
#       - pkgconfig
#       - dkms
# 
# - name: install latest module
#   dnf:
#     state: latest
#     name:
#       - "@nvidia-driver:latest-dkms"
