---
- name: install preconditions
  dnf:
    state: latest
    name:
      - kernel-devel
      - kernel-headers
      - gcc
      - make
      - dkms
      - acpid
      - libglvnd-glx
      - libglvnd-opengl
      - libglvnd-devel
      - pkgconfig
- name: enable rpm fusion
  dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version | default(42) }}.noarch.rpm"
    state: present

- name: enable rpm fusion nonfree
  dnf:
    name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version | default(42) }}.noarch.rpm"
    state: present

- name: makecache
  command: dnf makecache

- name: install nvidia drivers
  dnf:
    state: latest
    name:
      - akmod-nvidia
      - xorg-x11-drv-nvidia-cuda

- name: Install CUDA packages from RPMFusion
  dnf:
    state: latest
    name:
      - xorg-x11-drv-nvidia-cuda-libs
      - nvidia-driver-cuda
      - cuda-toolkit
      - nvidia-driver-NVML
      - nvidia-driver-devel

- name: Install additional CUDA development tools
  dnf:
    state: latest
    name:
      - gcc-c++
      - cmake
      - python3-pycuda
  tags: cuda_dev

- name: Set up CUDA environment variables
  blockinfile:
    path: /etc/profile.d/cuda.sh
    create: yes
    mode: '0644'
    block: |
      export PATH=/usr/local/cuda/bin:$PATH
      export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
      export CUDA_HOME=/usr/local/cuda
- name: Ensure nvidia kernel module is loaded
  modprobe:
    name: nvidia
    state: present
  ignore_errors: yes

- name: Check nvidia-smi is working
  command: nvidia-smi
  register: nvidia_smi_result
  ignore_errors: yes
  changed_when: false

- name: Display nvidia-smi output
  debug:
    var: nvidia_smi_result.stdout_lines
  when: nvidia_smi_result.rc == 0
