# https://wiki.archlinux.org/index.php/Lenovo_ThinkPad_X1_Carbon_(Gen_6)#Automatic_(Linux_Vendor_Firmware_Service)
# Still need to set a bunch of BIOS parameters

---
- name: Install tlp repo
  dnf:
      name: http://repo.linrunner.de/fedora/tlp/repos/releases/tlp-release.fc31.noarch.rpm
      state: present

# Problem is that copr for this is not up to date with fedora
#- name: Enable throttled copr
#  command: "dnf copr enable abn/throttled"
#  args:
#      creates: /etc/yum.repos.d/_copr:copr.fedorainfracloud.org:abn:throttled.repo

- name: Install fwupd
  dnf:
      pkg: ['fwupd', 'tlp', 'tlp-rdw', 'akmod-tp_smapi', 'akmod-acpi_call', 'kernel-devel', 'throttled']
      state: latest

- name: enable and start tlp
  service: name=tlp state=started enabled=yes

- name: enable and start throttled
  service: name=throttled state=started enabled=yes
