---
- hosts: all
  user: root
  gather_facts: no
  vars:
    username: hexgnu
    hostname: neptune.home
    email: matt@matthewkirk.com
    ansible_python_interpreter: /usr/bin/python3
    ssh_keygen_bits: 4096
    ssh_keygen_types:
      - ed25519
    python_versions:
        - 3.7.3
        - 2.7.16
  roles:
 #   - dmenu
 #   - docker
 #   - i3blocks
    - install_repos
    - elasticsearch
 #   - postgres
    - pyenv
 #   - ruby
 #   - slack
    - st
    - vim
 #   - zathura
 #   - zoom
 #   - wine
 #   - lenovo
  become_method: sudo
  become: true
  tasks:  
    - hostname:
        name: neptune.home

    # Someday revisit to implement better security for this.
    - service:
        name: sshd
        state: started

    - name: Install RPMFusion free
      tags: [personal]
      dnf:
        name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-31.noarch.rpm 
        state: present

    - name: Install RPMFusion non free
      tags: [personal]
      dnf:
        name: https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-31.noarch.rpm
        state: present

    #    - command: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
     #- command: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

    - name: Install libraries with dnf
      dnf: name={{ item }} state=latest
      tags: [system]
      with_items:
        - ShellCheck
        - neovim
        - cmake
        - direnv
        - dmenu
        - git
        - htop
        - pv
        - tmux
        - fedora-workstation-repositories
        - brave-browser
        - xclip
        - redhat-rpm-config
        - highlight
        - adobe-source-code-pro-fonts
        - npm
        - nodejs-yarn
        - lm_sensors
        - redshift-gtk
        - awscli
        - perl-Env
        - feh
        - fontawesome-fonts
        - community-mysql
        - vlc
        - lpf-spotify-client
        - dwm
        - dwm-user
        - libffi-devel
        - zlib-devel
        - bzip2
        - bzip2-devel
        - readline-devel
        - sqlite
        - sqlite-devel
        - openssl-devel
        - xz
        - xz-devel
        - i3
        - i3lock
        - i3status
        # - pam_yubico

    - name: Check out dotfiles
      become: true
      become_user: hexgnu
      git:
        update: false
        repo: git@github.com:/hexgnu/dotfiles.git
        dest: /home/hexgnu/git/personal/dotfiles

    - command: bin/dotfiles
      become: true 
      become_user: hexgnu
      args:
        chdir: /home/hexgnu/git/personal/dotfiles
