---
# ╔════════════════════════════════════════════════════════════════════════════╗
# ║                    ⚡️✨ SAILOR JUPITER SYSTEM CONFIG ✨⚡️                  ║
# ║                                                                            ║
# ║                         Protected by Jupiter                               ║
# ║                      Guardian of Thunder & Courage                         ║
# ║                                                                            ║
# ║                          木野 まこと (Makoto Kino)                         ║
# ╚════════════════════════════════════════════════════════════════════════════╝

- hosts: all
  user: root
  gather_facts: no
  vars:
    username: hexgnu
    hostname: jupiter.home
    email: matt@matthewkirk.com
    ansible_python_interpreter: /usr/bin/python3
    ssh_keygen_bits: 4096
    ssh_keygen_types:
      - ed25519
    fedora_version: 42
  
  pre_tasks:
    - name: "⚡ Sailor Jupiter Power Make Up! ⚡"
      shell: |
        echo ""
        echo "        ✨⚡🌸 TRANSFORMATION SEQUENCE INITIATED 🌸⚡✨"
        echo ""
        echo "              'Jupiter Star Power, Make Up!'"
        echo ""
        python3 {{ playbook_dir }}/sailor_jupiter_banner.py 2>/dev/null || true
        echo ""
        echo "        System configuration transformation beginning..."
        echo ""
      delegate_to: localhost
      run_once: true
      tags: always

  roles:
    - setup
    - keys
    - dotfiles  # Deploy dotfiles before other roles that depend on them
    - i3
    - i3blocks
    - flatpak
    - brave
    - st
    - vim
    - pyenv
    - nvm
    - podman
    - developer-tools
    - direnv
    - slack
    - zoom
    - nvidia
  become_method: sudo
  become: true
  
  tasks:  
    - hostname:
        name: jupiter.home

    # Someday revisit to implement better security for this.
    - service:
        name: sshd
        state: started

    - name: Install RPMFusion free
      tags: [personal]
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ fedora_version }}.noarch.rpm"
        disable_gpg_check: yes
        state: present

    - name: Install RPMFusion non free
      tags: [personal]
      dnf:
        disable_gpg_check: yes
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ fedora_version }}.noarch.rpm"
        state: present

  post_tasks:
    - name: "✨ Transformation Complete! ✨"
      shell: |
        echo ""
        echo "═══════════════════════════════════════════════════════════"
        echo "    🌸 'In the name of Jupiter, I'll punish you!' 🌸"
        echo ""
        echo "         System {{ hostname }} configured successfully!"
        echo "              Protected by Sailor Jupiter ⚡"
        echo "═══════════════════════════════════════════════════════════"
        echo ""
      delegate_to: localhost
      run_once: true
      tags: always
