---
# Pyenv installation for Python version management

- name: Install pyenv dependencies
  dnf:
    state: latest
    name:
      - make
      - gcc
      - gcc-c++
      - zlib-devel
      - bzip2
      - bzip2-devel
      - readline-devel
      - sqlite
      - sqlite-devel
      - openssl-devel
      - tk-devel
      - libffi-devel
      - xz-devel
      - python3-tkinter
      - findutils
      - git
      - tk-devel

- name: Clone pyenv repository for user
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: "/home/{{ username }}/.pyenv"
    update: yes

- name: Clone pyenv-virtualenv plugin
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/pyenv/pyenv-virtualenv.git
    dest: "/home/{{ username }}/.pyenv/plugins/pyenv-virtualenv"
    update: yes

- name: Clone pyenv-update plugin
  become: yes
  become_user: "{{ username }}"
  git:
    repo: https://github.com/pyenv/pyenv-update.git
    dest: "/home/{{ username }}/.pyenv/plugins/pyenv-update"
    update: yes

# Note: pyenv configuration is now managed in dotfiles repo
# The bashrc/bash_profile setup is handled by the dotfiles symlink

- name: Install Python 3.11 via pyenv
  become: yes
  become_user: "{{ username }}"
  shell: |
    source /home/{{ username }}/.bashrc
    pyenv install 3.11
  args:
    executable: /bin/bash
    creates: "/home/{{ username }}/.pyenv/versions/3.11.9"

- name: Install Python 3.12 via pyenv
  become: yes
  become_user: "{{ username }}"
  shell: |
    source /home/{{ username }}/.bashrc
    pyenv install -s 3.12
  args:
    executable: /bin/bash
    creates: "/home/{{ username }}/.pyenv/versions/3.12.4"

- name: Set global Python version to 3.12
  become: yes
  become_user: "{{ username }}"
  shell: |
    source /home/{{ username }}/.bashrc
    pyenv global 3.12
  args:
    executable: /bin/bash
