---
- name: Clone dotfiles repository
  git:
    repo: https://github.com/hexgnu/dotfiles.git
    dest: "/home/{{ username }}/git/personal/dotfiles"
    update: yes
  become: yes
  become_user: "{{ username }}"
  tags: [dotfiles]

- name: Run dotfiles setup script
  shell: |
    cd /home/{{ username }}/git/personal/dotfiles
    ./bin/dotfiles
  become: yes
  become_user: "{{ username }}"
  tags: [dotfiles]