---
- name: Install authoring tools (TeX, Pandoc, AsciiDoc)
  dnf:
    name:
      - texlive-base
      - texlive-xetex
      - pandoc
      - asciidoc
      - asciidoc-latex
    state: present
  tags: [packages, authoring, quick]

- name: Update authoring tools to latest
  dnf:
    name:
      - texlive-base
      - texlive-xetex
      - pandoc
      - asciidoc
      - asciidoc-latex
    state: latest
  tags: [update]
