---
- name: Install the latest version of Zettlr Texlive and Pandoc
  dnf:
    name:
      - texlive-base
      - texlive-xetex
      - pandoc
      - asciidoc
      - asciidoc-latex
    state: latest
