---
- name: deps for percona
  dnf: pkg={{item}} state=installed
  with_items:
    - perl-DBI
    - perl-Class-DBI-mysql
    - mysql-community-libs

- name: Link libmysqlclient.so.18 to /usr/lib64
  file:
    src: /usr/lib64/mysql/libmysqlclient.so.18
    dest: /usr/lib64/libmysqlclient.so.18
    state: link

- name: install percona-toolkit
  dnf:
    name: https://www.percona.com/downloads/percona-toolkit/2.2.20/RPM/percona-toolkit-2.2.20-1.noarch.rpm
    state: present
