---
- name: install packages
  dnf:
    state: latest
    name:
      - postgresql-server
      - postgresql-contrib
      - libpq-devel

- name: enable service
  service:
    name: postgresql
    enabled: true

- name: bootup
  shell: |
    FILE=/usr/local/postgresboot.t
    if test -f "$FILE"; then
      echo "$FILE exists."
      exit 0
    fi
    postgresql-setup --initdb --unit postgresql
  args:
    executable: /bin/bash

- name: start service now
  service:
    name: postgresql
    state: started


