---
- name: Install orc dependencies
  dnf: pkg={{item}} state=installed
  tags: [orc]
  with_items:
    - dnsmasq
    - docker
    - nginx

- name: setup orc
  git: repo=https://github.com/basecamp/orc.git dest=/root/.orc update=False
  tags: [orc]

- name: Add .devel to dnsmasq
  tags: [orc]
  template: src=../templates/devel.conf.j2 dest=/etc/dnsmasq.d/devel.conf

- name: install orc
  command: /root/.orc/bin/orc install
  tags: [orc]

