---
- name: install flatpak
  dnf: name=flatpak state=latest

- name: enable flatpak
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

# - name: install spotify
#   command: flatpak install -y flathub com.spotify.Client

- name: install zoom
  command: flatpak install -y flathub us.zoom.Zoom
