---
- name: Get latest phantomjs
  tags: phantomjs
  unarchive:
    creates: /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    src: https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-2.1.1-linux-x86_64.tar.bz2
    dest: /opt
    remote_src: yes

- name: symlink to /usr/local
  tags: phantomjs
  file:
    src: /opt/phantomjs-2.1.1-linux-x86_64/bin/phantomjs
    dest: /usr/local/bin/phantomjs
    state: link
