---
- name: Install ruby dependencies
  dnf:
    pkg: ['libffi-devel', 'readline-devel', 'openssl-devel', 'libyaml-devel', 'nodejs', 'gcc-c++', 'sqlite-devel']
    state: installed
  become: true
  tags: [ruby]
- name: setup rbenv
  become_user: "{{username}}"
  become: true
  git: repo=git@github.com:sstephenson/rbenv.git dest=~/.rbenv update=False
  tags: [ruby]

- name: setup ruby-build
  become: true
  become_user: "{{username}}"
  git: repo=git@github.com:sstephenson/ruby-build.git dest=~/.rbenv/plugins/ruby-build update=False
  tags: [ruby]

- name: Configure extensions for rbenv
  command: src/configure
  become: true 
  become_user: "{{username}}"
  args:
    chdir: /home/{{username}}/.rbenv

- name: Making extensions for rbenv
  command: make -C src
  become: true
  become_user: "{{username}}"
  args:
    chdir: /home/{{username}}/.rbenv

- name: Installing rubies
  command: rbenv install -s {{item}}
  become: true
  become_user: "{{username}}"
  with_items:
    - "{{ruby_versions}}"
