---
- name: Install mysql community repo
  dnf:
    name: https://dev.mysql.com/get/mysql57-community-release-fc24-8.noarch.rpm
    state: present

- name: Install mysql deps
  dnf: pkg={{item}} state=installed
  with_items:
    - jemalloc
    - mysql-community-server
    - mysql-community-devel
    - mysql-community-client

- name: Start mysql
  systemd: state=started name=mysqld.service

  #- name:
  # shell: "ack 'A temporary password is generated for root@localhost: (.*)' --output='$1' /var/log/mysqld.log | { read pw; mysqladmin -uroot -p$pw password {{ssh_keygen_password}}; }"

# https://www.if-not-true-then-false.com/2010/install-mysql-on-fedora-centos-red-hat-rhel/
#  Getting the password to work will require some finagling
#  Change password first
#  Uninstall plugin validate_password
#  Change password to blank
