---
- name: Direnv dependencies
  dnf:
    name: golang
    state: present

- name: Checkout direnv
  git:
    update: no
    repo: https://github.com/direnv/direnv.git
    dest: /opt/direnv

- name: Build direnv
  command: make install
  args:
    chdir: /opt/direnv
