---
- name: Add elasticsearch signing key
  rpm_key:
    state: present
    key: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Elastic.co yum repo
  yum_repository: 
    name: elasticsearch-2.x
    description: Elasticsearch 2.x repo
    gpgcheck: yes
    baseurl: https://packages.elastic.co/elasticsearch/2.x/centos
    gpgkey: https://packages.elastic.co/GPG-KEY-elasticsearch

- name: Install elasticsearch 2.x
  dnf: pkg={{item}} state=installed
  with_items:
    - elasticsearch

- name: Start elasticsearch
  service:
    name: elasticsearch
    state: started

