---
- name: Install elasticsearch dependencies
  dnf:
    pkg: ['java-devel', 'java']
    state: installed

- name: Add elasticsearch signing key
  rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

- name: Elastic.co yum repo
  yum_repository: 
    name: elasticsearch-7.x
    description: Elasticsearch 7.x repo
    gpgcheck: yes
    baseurl: https://artifacts.elastic.co/packages/7.x/yum
    gpgkey: https://artifacts.elastic.co/packages/7.x/yum

- name: Install elasticsearch 7.x
  dnf:
    pkg: elasticsearch
    state: installed

- name: Start elasticsearch
  service:
    name: elasticsearch
    state: started

