---
- name: Download slack file
  command: 'wget "https://downloads.slack-edge.com/linux_releases/slack-3.4.0-0.1.fc21.x86_64.rpm" -o /opt/slack.rpm'
  args:
      chdir: /opt
      creates: /opt/slack-3.4.0-0.1.fc21.x86_64.rpm

- name: Rpm install slack file
  yum: 
    name: /opt/slack-3.4.0-0.1.fc21.x86_64.rpm
    state: present
