---
- name: Build miniconda distribution based on latest
  become: true
  become_user: hexgnu
  shell:
    cmd: |
        mkdir -p ~/miniconda3 &&
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh &&
        bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3 &&
        rm -rf ~/miniconda3/miniconda.sh &&
        ~/miniconda3/bin/conda init bash
    creates: ~/miniconda3/bin/conda
